name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run Build Validation
      run: |
        echo "Release Pipeline Working!"
        python --version

    - name: Install zip
      run: sudo apt-get update && sudo apt-get install -y zip

    - name: Create Release Artifact
      run: zip -r release-package.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-artifact
        path: release-package.zip